accounts/urls.py
from re import template
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns=[
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),

    path('login/',
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
        ),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

photo/urls.py
from django.urls import path
from . import views

app_name='photo'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    path('post/',views.CreatePhotoView.as_view(),name='post'),
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name='photos_cat'),
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'),
    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name='photo_detail'),
    path('mypage/',views.MypageView.as_view(),name='mypage'),
    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name='photo_delete'),
]

photoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from tomlkit import document

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photo.urls')),
    path('',include('accounts.urls')),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'
         ),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
         name='password_reset_done'
         ),
    
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'),
         name='password_reset_confirm'
         ),

    path('reset/done',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'),
         name='password_reset_complete'
         ),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    pass

photo/models.py
from distutils.command.upload import upload
from tabnanny import verbose
from unicodedata import category
from click import command
from django.db import models
from matplotlib.pyplot import title
from accounts.models import CustomUser

class Category(models.Model):
    title=models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )

    def __str__(self):
        return self.title

class PhotoPost(models.Model):
    user=models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    
    category=models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )

    title=models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    comment=models.TextField(
        verbose_name='イメージ1',
    )

    image1=models.ImageField(
        verbose_name='イメージ１',
        upload_to='photos'
    )

    image2=models.ImageField(
        verbose_name='イメージ２',
        upload_to='photos',
        blank=True,
        null=True
    )

    posted_at=models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__(self):
        return self.title

accounts/forms.py
from attr import field
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=CustomUser
        fields=('username','email','password1','password2')

photo/forms.py
from attr import field
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    class Meta:
        model=PhotoPost
        fields=['category','title','comment','image1','image2']

accounts/views.py
from re import template
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class=CustomUserCreationForm
    template_name="signup.html"
    success_url=reverse_lazy('accounts:signup_success')

    def form_valid(self,form):
        user=form.save()
        self.object=user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name="signup_success.html"

# Create your views here.

photo/views.py
import imp
from re import template
from unicodedata import category
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from numpy import delete
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost
from django.views.generic import DetailView
from django.views.generic import DeleteView

# Create your views here.
class IndexView(ListView):
    template_name='index.html'
    queryset=PhotoPost.objects.order_by('-posted_at')
    paginate_by=9

@method_decorator(login_required,name='dispatch')

class CreatePhotoView(CreateView):
    form_class=PhotoPostForm
    template_name="post_photo.html"
    success_url=reverse_lazy('photo:post_done')

    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name="post_success.html"

class CategoryView(ListView):
    template_name='index.html'
    paginate_by=9
    def get_queryset(self):
        category_id=self.kwargs['category']
        categories=PhotoPost.objects.filter(category=category_id).order_by('-posted_at')
        return categories

class UserView(ListView):
    template_name='index.html'
    paginate_by=9

    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=PhotoPost.objects.filter(user=user_id).order_by('-posted_at')
        return user_list

class DetailView(DetailView):
    template_name='detail.html'
    model=PhotoPost

class MypageView(ListView):
    template_name='mypage.html'
    paginate_by=9
    def get_queryset(self):
        queryset=PhotoPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

class PhotoDeleteView(DeleteView):
    model=PhotoPost
    template_name='photo_delete.html'
    seccess_url=reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Log in</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
      crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css" %} rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  {% if form.errors %}
    <p style="color:red">ユーザー名とパスワードが一致しません</p>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <img  class="mb-4" 
          src={% static "image/bootstrap-logo.svg" %}
          alt="" 
          width="72" 
          height="57">
    <h1 class="h3 mb-3 fw-normal">Please Log in</h1>

    <label for="Username" class="visually-hidden">User name</label>
    <input  type="text"
            name="username"
            id="id_username"
            maxlength="150"
            autocapitalize="none"
            autocapitalize="username"
            class="form-control"
            placeholder="ユーザ名"
            required autofocus>
    
    <label for="Password" class="visually-hidden">Password</label>
    <input  type="password"
            name="password"
            id="id_password"
            autocomplete="current-password"
            class="form-control"
            placeholder="パスワード"
            required>
    
    <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">
    <br><br>
    <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a></p>
    <input  type="hidden"
            name="next"
            value="{% url 'photo:index' %}">
  </form>
  </main>
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}Log out{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">

            <h3>ログアウトしました</h3>
            <p><a href="{% url 'photo:index' %}">トップページへ</a></p>
        {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Reset password{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか</h3>
                <p>
                    登録済みのメールアドレスを入力してください
                    パスワードリセットのリンクを記載したメールをすぐにお届けします。
                </p>
                <br>
            <form action="" method="POST" class="text-center">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <a href="{% url 'photo:index' %}">Photo Gallery</a>
            <hr>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
<head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>

<body>
    <div class="pad">
        <h2>パスワードがリセットされました。</h2>
        <p>
            Your Password has been set. You may go ahead and login
        </p>
        <br>
        <a href="{% url 'photo:index' %}">Photo Galleryのトップページへ</a>
    </div>
</body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
<head>
    <style>
        .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
        }
    </style>
</head>

<body>
    <div class="pad">
        <h2>Photo Gallery</h2>
        <h4>
            新しいパスワードを2回入力してください。これにより、正しく入力できたことが確認されます。
        </h4>
        <br />
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="パスワードリセット"/>
        </form>
    </div>
</body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}Reset password reset{% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードリセットのリセット手順をメールで送信しました。
                    メールはすぐ届きます。</h5>
                <br>
                <h6>メールが届かない場合は、登録済みのメールアドレスであるかを確認し、迷惑メールフォルダも確認してみてください</h6>
                <br>
                <a "{% url 'photo:index' %}">Photo Gallery</a>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset2">
                <h3>サインアップ</h3>
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </p>
                    {% endfor %}
                <p style="color:red">
                    メールアドレスはパスワードをリセットする際に必要になりますので、登録しておくことをお勧めします。
                </p>
                <input type="submit" value="Sign up">
                </form>
                <br>
            <p><a href="{% url 'photo:index' %}">
                登録をやめてトップページに戻る</a>
            </p>
            </div>
        </div>
    </div>
    {% endblock %}
    

accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}Registration Complete{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>登録が完了しました</h3>
                <p><a href="#">ログインはこちら</a></p> 
            </div>
        </div>
    </div>
    {% endblock %}

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %} {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
          crossorigin="anonymous">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう！</h4>
          <p class="text-muted">
          誰でも参加できる写真投稿サイトです。
          自分で撮影した写真なら何でもオッケー！
          でも、カテゴリに属する写真に限ります。
          コメントも付けてください！
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <!-- ナビゲーションメニュー　-->
            {% if user.is_authenticated %}
            <li><a href="{% url 'photo:mypage' %}" class="text-white">マイページ</a></li>
            <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
            <li><a href="{% url 'password_reset' %}" class="text-white">パスワードのリセット</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
            <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
            <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Photo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  {% block contents %}{% endblock %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
            crossorigin="anonymous"></script>

      
  </body>
</html>

photo/templates/detail.html
{% extends 'base.html' %}
{% block title %}Photo Detail{% endblock %}

{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
        <h2>{{object.title}}</h2>
        <p>{{object.comment}}</p>
        <br>
        <p>{{object.posted_at}}</p>
        <p><img src="{{ object.image1.url }}"></img></p>
        {% if object.image2 %}
        <p><img src="{{ object.image2.url }}"></img></p>
        {% endif %}

        {% if request.user == object.user %}
        <form method="POST">
        <a  href="{% url 'photo:photo_delete' object.pk %}"
            class="btn btn-primary my-2">削除する</a>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

{% block contents %}

{% include "photos_title.html" %}

{% include "photos_list.html" %}

{% include "pagination.html" %}

{% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}
{% block contents %}
{% if user.is_authenticated %}
<br>
<div style="text-align:center">
<h4>{{user.username}}さんの投稿はありません</h4>
{% if object_list.count == 0 %}
{% else %}
<p>投稿<strong>{{ object_list.count }}</strong>件</p>
{% endif %}
<a href="{% url 'photo:post' %}">投稿する</a>
</div>
<hr>
{% endif %}

{% include "photos_list.html" %}
{% include "pagination.html" %}
{% endblock %}

photo/templates/pagination.html
{% if is_paginated %}
<ul class="pagination" style="justify-content:center">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a  class="page-link"
            href="?page={{ page_obj.previous_page_number }}"
            aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
        <span class="page-link">{{num}}</span>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{num}}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
        <a  class="page-link"
            href="?page={{page_obj.next_page_number}}"
            aria label="Next">
        <span aria-hidden="true">&raquo;</span>
    </li>
    {% endif %}
    </ul>
    {% endif %}

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img  src="{{ record.image1.url }}" 
                  class="bd-placeholder-img card-img-top" 
                  width="100%" 
                  height="225" 
                  xmlns="http://www.w3.org/2000/svg" 
                  role="img" 
                  aria-label="Placeholder: Thumbnail" 
                  preserveAspectRatio="xMidYMid slice" 
                  focusable="false">
              <title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
            </img>

            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" 
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                    View
                  </button>
                  <button type="button" 
                          class="btn btn-sm btn-outline-secondary" 
                          onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <a href="{% url 'photo:user_list' user=record.user.id %}">
                  <small class="text-muted">{{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
        コメントを見て写真に書かれた世界に思いを馳せましょう。
        素敵な写真とコメントをお待ちしています。
        </p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

photo/templates/post_photo.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}

    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>タイトル</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>画像1</th>
                            <td>{{ form.image1 }}</td>
                        </tr>
                        <tr>
                            <th>画像2</th>
                            <td>{{ form.image2 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}
{% block title %}Post Success{% endblock %}

    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました</h4>
            </div>
        </div>
    </div>
    {% endblock %}